---
apiVersion: v1
kind: Service
metadata:
  name: cornerstone-verifier-agent
  namespace: cornerstone-verifier
spec:
  type: ClusterIP         # Default type (ClusterIP), NodePort, LoadBalancer
  selector:
    app: cornerstone-verifier-agent
  ports:
    - name: admin-port
      port: 8001          #service port http
      targetPort: 8001
      protocol: TCP
    - name: http-port
      port: 8000          #service port http
      targetPort: 8000 
      protocol: TCP


# kubectl port-forward service/cornerstone-verifier-agent 8280:8280 -n cornerstone-verifier
# kubectl port-forward deployment.apps/cornerstone-verifier-agent 8280:8280 -n cornerstone-verifier

# localhost:8280/ 

