---
# https://issuer-agent-admin.iamza-sandbox.com
# k8s-cornerst-cornerst-d7a30c27d5
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cornerstone-verifier-admin-ingress
  namespace: cornerstone-verifier
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    ingress.kubernetes.io/ssl-redirect: "false"    
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:af-south-1:149875424875:certificate/f862af7f-40b5-4d20-8960-a746f637aff8
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cornerstone-verifier-agent
            port:
              number: 8001
