---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cornerstone-verifier
  namespace: cornerstone-verifier
  labels:
    app: cornerstone-verifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cornerstone-verifier
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: cornerstone-verifier
    spec:
      containers:
        - name: cornerstone-verifier
          image: 149875424875.dkr.ecr.af-south-1.amazonaws.com/cornerstone-verifier:latest
          imagePullPolicy: Always
          ports:
            - name: server-port
              containerPort: 8280
              protocol: TCP
          envFrom:
            - configMapRef:
                name: cornerstone-verifier-configmap
          env:
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cornerstoneverifiersecret
                  key: emailpw
            - name: EMAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cornerstoneverifiersecret
                  key: emailusername
            - name: EMAIL_SMTP_SERVER
              valueFrom:
                secretKeyRef:
                  name: cornerstoneverifiersecret
                  key: emailsmtpserver
            - name: EMAIL_SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: cornerstoneverifiersecret
                  key: emailsmtpport
